# Generated by Django 5.0.7 on 2024-09-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('product', 'Product Offer'), ('category', 'Category Offer')], max_length=20),
        ),
    ]
