# Generated by Django 5.0.7 on 2024-08-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_couponusage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CouponUsage',
        ),
    ]
