# Generated by Django 5.0.7 on 2024-08-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0002_remove_category_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='max_quantity_per_user',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
