# Generated by Django 5.0.7 on 2024-08-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_productvariant_max_quantity_per_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricing',
        ),
    ]
