# Generated by Django 5.0.7 on 2024-08-07 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
    ]
