# Generated by Django 5.0.7 on 2024-08-08 12:36

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0008_productvariant_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image1',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/admin/imgs'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image2',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/admin/imgs'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image3',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='static/admin/imgs'),
        ),
    ]
