# Generated by Django 5.0.7 on 2024-08-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0009_remove_product_image1_remove_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
