# Generated by Django 5.0.7 on 2024-08-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
