# Generated by Django 5.0.7 on 2024-09-14 13:03

import django.db.models.deletion
import product_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0016_populate_brand_for_all_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=product_management.models.get_default_brand, on_delete=django.db.models.deletion.CASCADE, to='product_management.brand'),
        ),
    ]
