# Generated by Django 5.0.7 on 2024-08-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0006_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/admin/imgs'),
        ),
    ]
