# Generated by Django 5.0.7 on 2024-08-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0008_wallet_wallethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_new_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='new_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
