# Generated by Django 5.0.7 on 2024-08-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0009_account_is_new_email_verified_account_new_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
