# Generated by Django 5.0.7 on 2024-08-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0010_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
