# Generated by Django 5.0.7 on 2024-08-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0011_alter_wallethistory_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
