# Generated by Django 5.0.7 on 2024-09-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price_at_addition',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
