# Generated by Django 5.0.7 on 2024-09-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_price_at_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='price_at_addition',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
