# Generated by Django 5.0.7 on 2024-08-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderaddress',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
