# Generated by Django 5.0.7 on 2024-08-11 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderaddress_user'),
        ('user_log', '0007_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_log.address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='OrderAddress',
        ),
    ]
