# Generated by Django 5.0.7 on 2024-08-26 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_applied_coupon_order_coupon_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='applied_coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='coupon_discount',
        ),
    ]
